fun main() {
    println("\t\tTipos Em Kotlin")
    println("_________________________________________")
    println("Byte")
    println("valor mínimo:"+ Byte.MIN_VALUE)
    println("valor máximo:"+ Byte.MAX_VALUE)
    println("tamanho (em bytes):"+ Byte.SIZE_BYTES)
    println("_________________________________________")
    println("Short")
    println("valor mínimo:"+ Short.MIN_VALUE)
    println("valor máximo:"+ Short.MAX_VALUE)
    println("tamanho (em bytes):"+ Short.SIZE_BYTES)
    println("_________________________________________")
    println("Int")
    println("valor mínimo:"+ Int.MIN_VALUE)
    println("valor máximo:"+ Int.MAX_VALUE)
    println("tamanho (em bytes):"+ Int.SIZE_BYTES)
    println("_________________________________________")
    println("Long")
    println("valor mínimo:"+ Long.MIN_VALUE)
    println("valor máximo:"+ Long.MAX_VALUE)
    println("tamanho (em bytes):"+ Long.SIZE_BYTES)
    println("_________________________________________")
    println("Float")
    println("valor mínimo:"+ Float.MIN_VALUE)
    println("valor máximo:"+ Float.MAX_VALUE)
    println("_________________________________________")
    println("Double")
    println("valor mínimo:"+ Double.MIN_VALUE)
    println("valor máximo:"+ Double.MAX_VALUE)
    println("_________________________________________")
    println("Char")
    println("tamanho (em bytes):"+ Char.SIZE_BYTES)
    println("_________________________________________")
}
